name: build-toolchain-powerpc64-linux-gnu

env:
  GPG_TTY: $(tty)
  ___TARGETARCH: "powerpc64-linux-gnu"
  SCCACHE_DIR: "/sccache/"
  C_COMPILER_LAUNCHER: "sccache"
  CXX_COMPILER_LAUNCHER: "sccache"
  SCCACHE_GHA_ENABLED: on
on:
  push:
    paths:
        - "powerpc64-linux-gnu/**"
        -  ".github/workflows/build-powerpc64-linux-gnu.yml"
  workflow_dispatch:

jobs:
  toolchainbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure sccache
      uses: actions/github-script@v6
      with:
        script: |
             core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
             core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - name: Build
      run: |
        echo ${{ github.event.name }}
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd sccache
        mkdir -p $SCCACHE_DIR
        echo CC=\"sccache gcc\" >> /etc/makepkg.conf
        echo CXX=\"sccache g++\" >> /etc/makepkg.conf
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        cd ${___TARGETARCH}/linux-api-headers
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --nocheck --skippgpcheck
        cd ../binutils
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --nocheck --skippgpcheck
        cd ../gcc-stage1
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --nocheck --skippgpcheck --nodeps
        cd ../glibc-headers
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --nocheck --skippgpcheck
        cd ../gcc-stage2
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        yes y | sudo -u builder makepkg -fsir --nocheck --skippgpcheck --nodeps
        cd ../glibc
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        yes y | sudo -u builder makepkg -fsir --nocheck --skippgpcheck
        cd ../gcc
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        yes y | sudo -u builder makepkg -fsir --nocheck --skippgpcheck
        cd ../glibc
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --skippgpcheck
        cd ../gcc
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --skippgpcheck
        cd ../gdb
        pacman -Syu --noconfirm --needed base-devel sudo git fd xz ncurses expat python guile gdb-common mpfr libelf source-highlight libmpc zlib libisl zstd
        sudo -u builder makepkg -fsir --noconfirm --skippgpcheck
        cd ../
        rm -rf gcc-stage1 gcc-stage2 glibc-headers
        fd --glob '*tar.zst' -X mv {} ../
    - name: Upload Toolchain
      uses: actions/upload-artifact@v3
      with:
          name: toolchain-powerpc64-linux-gnu
          path: "**.tar.zst"