name: build-toolchain-ppc64

env:
  GPG_TTY: $(tty)

on:
  push:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        echo ${{ github.event.name }}
        pacman -Syu --noconfirm base-devel crosstool-ng gnupg make
        mv ppc64.config .config
        ct-ng build
    - name: Upload Toolchain
      uses: actions/upload-artifact@v3
      with:
          name: packages
          path: /opt/*